### ISSUE TITLE
关于自动构建

### ISSUE THREAD

**Issue by lakejason0** [lakejason0/mcwzh-meme-resourcepack#11]
**你的特性建议和某个问题相关吗？请描述。**
这个repo要自己转码构建，构建出来还不能用，好麻烦哦。

**描述你喜欢的解决方法**
使用GitHub Action自动转码release，并删除两个branch。

**描述你想到的其他解决方案**
维持原状。

**附加信息**
由我提出，猫猫负责构建。

**Comment by AlPha5130** [comment]
现在我有一个折中方案：写一段Python代码，运行即可构建出mcpack。可以只留下master分支。但仍需手动release和上传assets。准备测试是否可以自动完成。

**Comment by lakejason0** [comment]
> 现在我有一个折中方案：写一段Python代码，运行即可构建出mcpack。这样可以只留下master分支，但仍需手动release和上传assets。准备测试是否可以自动完成。

似乎没有听懂（mcpack是什么）。的确解决方案并没有达到预期请求（自动构建并release）。

**Comment by dianliang233** [comment]
Java版哪里来的 `.mcpack` 啊...

**Comment by lakejason0** [comment]
看到了一个git-bash action，可以执行commit的样子。
