### ISSUE TITLE
梗体中文材质包的内容改进

### ISSUE THREAD

**Issue by bbz-233** [lakejason0/mcwzh-meme-resourcepack#215]
我发现材质包有些内容还不够梗体中文。以下是我修改的内容

格式：

梗体中文原文
→修改后文字

正文：

生鲜鳕鱼
→《使 命 召 唤》

鳕鱼铁桶
→桶装《使命召唤》

沸腾鳕鱼
→沸腾的《使命召唤》

生鲜鳕鱼：啊我死了
→《使命召唤》：啊我死了

桶装奶
→Let's 牛乳dance!

流浪奸商：饮用桶装奶
→流浪奸商：Let's 牛乳dance!

阿米娅：喊叫
→阿米娅：大 喊 大 叫

蜂子：啊我死了
→蜂子：啊我蜂了

轨
→轨!

原谅石
→【你知道吗】不小心打到村民用原谅石跟村民交易会获得村民原谅

附加信息

“Let's 牛乳dance!”是个音游梗,出自《Oshama Scramble》

《使命召唤》的英文简写是COD,鳕鱼的英文也是cod,叫鳕鱼为《使命召唤》没毛病吧

之前投错地方，又不会用拉动请求，所以重新投到这里了

**Comment by Ba-Bao-zhou** [comment]
马：awsl
→马：我免费了
因为死马=飞马（参考YMFM） > 马：我自由了=马：我免费了（机翻）

**Comment by Dianliang233** [comment]
> 马：awsl →马：我免费了 因为死马=飞马（参考YMFM） > 马：我自由了=马：我免费了（机翻）

此issue已关闭，请新开issue以便追踪
