### ISSUE TITLE
关于自定义字符串

### ISSUE THREAD

**Issue by lakejason0** [lakejason0/mcwzh-meme-resourcepack#22]
**你的特性建议和某个问题相关吗？请描述。**
关于版权的另一种写法。

**描述你喜欢的解决方法**
新增标识符“resourcepack.authors”，填入参与的部分人员。

**描述你想到的其他解决方案**
在Description里标注上。

**附加信息**
可能会导致比较en_US.json时无法对齐。

**Comment by dianliang233** [comment]
反对。如果有必要的话可以写进闪烁标语和比较隐蔽的位置（seargesays等等）。

**Comment by AlPha5130** [comment]
另外整个资源包也需要注上版权声明，仓库里需要License。

**Comment by lakejason0** [comment]
嗯。有必要的话还得来一个生草闪烁标语？仓库的License我不知道选什么。

**Comment by lakejason0** [comment]
> 嗯。有必要的话还得来一个生草闪烁标语？仓库的License我不知道选什么。

根据电量的建议选择了CC BY-SA 4.0。

**Comment by AlPha5130** [comment]
>反对。如果有必要的话可以写进闪烁标语和比较隐蔽的位置（seargesays等等）。
Java版里已经没有seargesays了，只有基岩版才有。

**Comment by lakejason0** [comment]
在模型文件里注明了皮肤的ID（除了猫猫的因为它真的只是黑猫）。

**Comment by lakejason0** [comment]
pack.mcmeta会不会略过自己不认得的字段？要是这样我们就可以在pack.mcmeta里写上。

**Comment by SkyEye-FAST** [comment]
基岩版自带metadata下有license，我不知道Java版会不会怎么样……
顺便seargesays的话Ff自己改了一条，中文Minecraft Wiki提醒您：译名千万条……

**Comment by lakejason0** [comment]
> 基岩版自带metadata下有license，我不知道Java版会不会怎么样……
> 顺便seargesays的话Ff自己改了一条，中文Minecraft Wiki提醒您：译名千万条……

可还行，不过Java版没法搞Searge says。
