### ISSUE TITLE
旧版本的资源包格式

### ISSUE THREAD

**Issue by AlPha5130** [lakejason0/mcwzh-meme-resourcepack#34]
**描述**
资源包无法应用到1.12.2及以下版本。

**复现步骤**
在这些版本中无法正常加载资源包。

**正常行为**
资源包应当正常加载。

**版本**
所有1.12.2及以下版本的Minecraft。

**其他内容**
由于1.13的Minecraft对语言文件格式进行了重大更改，导致不兼容。

**Comment by AlPha5130** [comment]
文件格式可以用python自动转换，同时也可以将block.<something>替换为tile.<something>。

**Comment by lakejason0** [comment]
做，都可以做。

**Comment by lakejason0** [comment]
遇到了技术性困难，推迟。

**Comment by lakejason0** [comment]
通过映射表的方式解决了一部分。现在需要的就是制作映射表（

**Comment by dianliang233** [comment]
緊急召集人員製作映射表，很簡單，只需要做選擇。無償，詳訊 @lakejason0 ！

**Comment by lakejason0** [comment]
除去命令，都做好了。
