### ISSUE TITLE
关于 Netherite 系列译名的改进意见

### ISSUE THREAD

**Issue by RicoloveFeng** [lakejason0/mcwzh-meme-resourcepack#41]
考虑将 Netherite 翻译为 “黑色高级”

示例：
* Netherite Scrap 黑色高级碎片
* Netherite Ingot 黑色高级锭
* Netherite Pickaxe 黑色高级镐
* Netherite Chestplate 黑色高级胸甲

**Comment by lakejason0** [comment]
？你是……哪位？方便提供一下Gamepedia ID吗？

**Comment by RicoloveFeng** [comment]
卡狗 desu
wiki id: Kakagou12341

**Comment by lakejason0** [comment]
哦卡卡狗啊，那没事了

**Comment by lakejason0** [comment]
我提交以下pr

**Comment by lakejason0** [comment]
pr已创建，等待其他贡献者。

**Comment by lakejason0** [comment]
注意：直接使用了查找替换，因为部分条目已经有其他梗。
