### ISSUE TITLE
网页构建Mod选项

### ISSUE THREAD

**Issue by AlPha5130** [lakejason0/mcwzh-meme-resourcepack#51]
**描述**
Mod选项似乎不能正常工作。

**复现步骤**
复现漏洞的步骤：
1.Mod内容选择“所有”
2.开始构建
3.生成了没有Mod的包。

**正常行为**
应该生成含有所有Mod的包。

**截图**
<img width="960" alt="批注 2020-04-05 205807" src="https://user-images.githubusercontent.com/34984380/78498955-4b3c8c80-7780-11ea-9557-7243c9d14027.png">

**Comment by lakejason0** [comment]
有关参数提交的部分都是由网页端处理的。正在查看js的部分。

**Comment by lakejason0** [comment]
最新的commit中已经尝试修复了该问题。
