### ISSUE TITLE
advancements.nether.uselodestone.title

### ISSUE THREAD

**Issue by lihuoran-oier** [lakejason0/mcwzh-meme-resourcepack#57]
**你的特性建议和某个问题相关吗？请描述。**
简明扼要地描述问题所在。例：我在[...]的时候很不爽。

**描述你喜欢的解决方法**
磁石何时引我还

**描述你想到的其他解决方案**
简明扼要地描述你考虑到的的其他建议、解决方法或特性。

**附加信息**
可以在此加上事情的来龙去脉或者关于这个特性建议的截图。

**Comment by lakejason0** [comment]
这个算新版同步问题吧？使用最新版即可。

**Comment by lakejason0** [comment]
等一下，啥？标识符不一样？

**Comment by lakejason0** [comment]
@AlPha5130 有时间的话看看是不是MJSB了

**Comment by lihuoran-oier** [comment]
233

**Comment by lihuoran-oier** [comment]
其实是新版的进度

**Comment by lihuoran-oier** [comment]
20w20a加的

**Comment by lihuoran-oier** [comment]
但这个标准译名还没定

**Comment by lihuoran-oier** [comment]
加了好几个新成就 快去研究梗中的翻译

**Comment by lihuoran-oier** [comment]
就剩一个译名还没定了

**Comment by AlPha5130** [comment]
这一条是20w20a新加的，和旧的无关

**Comment by lakejason0** [comment]
更改成了“罗德岛是你家”。

**Comment by lihuoran-oier** [comment]
罗德岛是哪里的梗啊...没听过

**Comment by lakejason0** [comment]
> 罗德岛是哪里的梗啊...没听过

看[萌娘百科](https://zh.moegirl.org/明日方舟)。
