### ISSUE TITLE
网页打包上方appbar在移动设备上显示顺序错误

### ISSUE THREAD

**Issue by dianliang233** [lakejason0/mcwzh-meme-resourcepack#74]
网页打包上方appbar在移动设备上只显示右侧的链接，左侧的标题被隐藏了。

## 图片
![51D26C38C5968A040D577E55AB5EF248](https://user-images.githubusercontent.com/45287180/86523267-77110080-be9c-11ea-8e01-453f51e6571b.jpg)

**Comment by lakejason0** [comment]
我觉得换成图片logo即可解决这个问题。

**Comment by XxLittleCxX** [comment]
> 我觉得换成图片logo即可解决这个问题。

电量的意思难道不是右上角东西太多了吗

**Comment by lakejason0** [comment]
> > 我觉得换成图片logo即可解决这个问题。
> 
> 电量的意思难道不是右上角东西太多了吗

我认为达成目的即可（

**Comment by dianliang233** [comment]
> > > 我觉得换成图片logo即可解决这个问题。
> > 
> > 
> > 电量的意思难道不是右上角东西太多了吗
> 
> 我认为达成目的即可（

关键是达不成目的。

**Comment by lakejason0** [comment]
> > > > 我觉得换成图片logo即可解决这个问题。
> > > 
> > > 
> > > 电量的意思难道不是右上角东西太多了吗
> > 
> > 
> > 我认为达成目的即可（
> 
> 关键是达不成目的。

做成sidebar？

**Comment by dianliang233** [comment]
> > > > > 我觉得换成图片logo即可解决这个问题。
> > > > 
> > > > 
> > > > 电量的意思难道不是右上角东西太多了吗
> > > 
> > > 
> > > 我认为达成目的即可（
> > 
> > 
> > 关键是达不成目的。
> 
> 做成sidebar？

对。

**Comment by XxLittleCxX** [comment]
![image](https://user-images.githubusercontent.com/26459759/86911439-e5301e80-c14d-11ea-9b12-bf1eab313d5e.png)
![image](https://user-images.githubusercontent.com/26459759/86911451-eb25ff80-c14d-11ea-897c-d67442fa457d.png)

我觉得这能稍微救一下

**Comment by XxLittleCxX** [comment]
![image](https://user-images.githubusercontent.com/26459759/86911484-fed16600-c14d-11ea-98c8-5f51d7c2a2e0.png)

但是这个menu里面东西不齐及其难受

**Comment by dianliang233** [comment]
我待会调整一下。

------------------ 原始邮件 ------------------
发件人: _LittleC_ <notifications@github.com&gt;
发送时间: 2020年7月8日 19:06
收件人: lakejason0/mcwzh-meme-resourcepack <mcwzh-meme-resourcepack@noreply.github.com&gt;
抄送: Dianliang <2917830075@qq.com&gt;, Assign <assign@noreply.github.com&gt;
主题: 回复：[lakejason0/mcwzh-meme-resourcepack] 网页打包上方appbar在移动设备上显示顺序错误 (#74)








但是这个menu里面东西不齐及其难受

**Comment by XxLittleCxX** [comment]
> 我待会调整一下。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: _LittleC_ <notifications@github.com&gt; 发送时间: 2020年7月8日 19:06 收件人: lakejason0/mcwzh-meme-resourcepack <mcwzh-meme-resourcepack@noreply.github.com&gt; 抄送: Dianliang <2917830075@qq.com&gt;, Assign <assign@noreply.github.com&gt; 主题: 回复：[lakejason0/mcwzh-meme-resourcepack] 网页打包上方appbar在移动设备上显示顺序错误 (#74) 但是这个menu里面东西不齐及其难受 — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.

![image](https://user-images.githubusercontent.com/26459759/86920547-87570300-c15c-11ea-8547-b987414a5afe.png)

改成这样了

**Comment by dianliang233** [comment]
还行，暂时这样吧。
------------------ 原始邮件 ------------------
发件人: _LittleC_ <notifications@github.com&gt;
发送时间: 2020年7月8日 20:49
收件人: lakejason0/mcwzh-meme-resourcepack <mcwzh-meme-resourcepack@noreply.github.com&gt;
抄送: Dianliang <2917830075@qq.com&gt;, Assign <assign@noreply.github.com&gt;
主题: 回复：[lakejason0/mcwzh-meme-resourcepack] 网页打包上方appbar在移动设备上显示顺序错误 (#74)






我待会调整一下。
…
------------------ 原始邮件 ------------------ 发件人: LittleC <notifications@github.com&gt; 发送时间: 2020年7月8日 19:06 收件人: lakejason0/mcwzh-meme-resourcepack <mcwzh-meme-resourcepack@noreply.github.com&gt; 抄送: Dianliang <2917830075@qq.com&gt;, Assign <assign@noreply.github.com&gt; 主题: 回复：[lakejason0/mcwzh-meme-resourcepack] 网页打包上方appbar在移动设备上显示顺序错误 (#74) 但是这个menu里面东西不齐及其难受 — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.



改成这样了

**Comment by dianliang233** [comment]
Deployed sccessfully, closing this
