### ISSUE TITLE
关于木剑的名称

### ISSUE THREAD

**Issue by InstrumentMan** [lakejason0/mcwzh-meme-resourcepack#76]
我在浏览物品时发现**木剑**的名字毫无变化，但我认为也许可以换一个名字。

个人认为可以改为**桃木剑**。

当然也可以改成**劣质桃木剑**，以及一些*奇怪*的名字。

仅为个人建议，具体如何~~由您们决定~~。

**Comment by lakejason0** [comment]
语气没必要这样……
