### ISSUE TITLE
更新物品条目、跟进1.16快照新增内容

### ISSUE THREAD

**Issue by dianliang233** [lakejason0/mcwzh-meme-resourcepack#8]
**你的特性建议和某个问题相关吗？请描述。**
我在看到大家咕咕咕的时候很不爽。

**描述你喜欢的解决方法**
我要大家一起快点把新东西解决掉。

**描述你想到的其他解决方案**
除了更新，难道还有解决方案吗？

**附加信息**
事情的来龙去脉 - 大家咕咕咕了。
截图：
!(https://wx2.sinaimg.cn/mw690/006Kzn7ygy1gbmkevdym4j30v10huh5o.jpg)

**Comment by lakejason0** [comment]
译名已经跟进了，你眼睛呢？
