### ISSUE TITLE
一堆建议

### ISSUE THREAD

**Issue by Light-Beacon** [lakejason0/mcwzh-meme-resourcepack#80]
1.镀金 -> 镀黄油 ![image](https://user-images.githubusercontent.com/49828867/86549476-51eec180-bf72-11ea-88fb-f888474491a1.png)（这个应该算Bug吧）
2.拌饭用的骨灰 -> 金坷垃
图都做好了：
![image](https://user-images.githubusercontent.com/49828867/86554746-0a236680-bf81-11ea-8863-b5e5424b8d68.png)
效果
![image](https://user-images.githubusercontent.com/49828867/86550689-a8113400-bf75-11ea-8122-d777147c2132.png)
3.滨菊 -> 菊花!
4.僵尸 -> 脏比
5.羽毛 -> 鸡毛
6.纸 -> 试卷
7.复读型滥权方块（循环命令方块）此处改为复读（顺带方块改名叫复读机吧）
![image](https://user-images.githubusercontent.com/49828867/86551644-3c7c9600-bf78-11ea-807d-8f77b1ecf909.png)
8.鳞甲 -> 原谅甲
9.村民 -> 奸商
10.1. 掠夺者 -> 远程型鬼子
10.2. 卫道士 -> 近战型鬼子
10.3. 唤魔者 -> 膜法型鬼子
10.4. 劫掠兽 -> 恶犬型鬼子
11. 狙击手的对决（进度） -> 我卢本伟没有开挂
12. 瞄准目标（进度） -> 瞄准目♂ 标
13. 岩浆膏 -> 鼻涕球裹上镀黄油法国面包糠，隔壁小孩都馋哭了
14. 百猫全书（进度） -> 百猫铲屎官
14.1 驯服所有种类的猫（进度描述↑）-> 为所有种类的猫铲屎
15. 在游戏尽头的城市（进度） -> 蒙达鲁克硫斯伯古比奇巴勒城!
16. 探索的时光（进度） -> 踏破祖安靴有觅处!
17. 木炭 -> 活性C
18. 视频设置 -> 瞎眼设置
19. 聊天（设置） -> 哔哔（或BB）
20. 熊孩子的作案工具（其实我觉得都可） -> 步步高打火机
21. 锻造台 -> 玩个锤子台
22. 物品修复和重命名（铁砧GUI） -> 玩个锤子
22. 苹果 -> 王后给的苹果
23. 水瓶 -> 农 夫 山 泉
24. 玻璃瓶 -> 可回收垃圾
25. 抗火药水 -> 抗炼丹炉药水
26. 制图台 -> 几何画板
27. 海底遗迹探险家地图 -> 海之霸餐厅用餐券附地图
28. 交易（村民GUI） -> py交易（或黑市贸易）
29. 砂砾 -> 牛顿快乐砾
30. 羽落 -> 多考虑了空气阻力
31. 直接连接（多人游戏） -> 直接怼

**Comment by lakejason0** [comment]
正在讨论。
