### ISSUE TITLE
增加内容

### ISSUE THREAD

**Issue by dujinhuachinaeddie** [lakejason0/mcwzh-meme-resourcepack#89]
竹子：王阳明的感冒
下界之星：夜空中最致盲的那颗星
缓慢药水：BMCLAPI    原因：BMCLAPI下载超慢
还有一些想法不太成熟，一会儿更新

**Comment by lakejason0** [comment]
已删除一个不合适的提议。

**Comment by dujinhuachinaeddie** [comment]
OK

**Comment by dujinhuachinaeddie** [comment]
铁头盔：无痛练功（铁头功）

**Comment by lakejason0** [comment]
王阳明……格物致知可还行，不过不确定是不是都知道。也许换个表述辨识度会更高？
下界之星已经有白金之星了，so.jpg
BMCLAPI……我只想说MCD比这慢多了。
铁头盔改的……辨识度也不高感觉。

**Comment by dujinhuachinaeddie** [comment]
好吧

**Comment by dujinhuachinaeddie** [comment]
绿宝石：这玩意我出三个土块儿

**Comment by lakejason0** [comment]
如果有能力的话可以直接提pull request，会更方便一些。

**Comment by dujinhuachinaeddie** [comment]
OK但是没有能力，我不会用

**Comment by lakejason0** [comment]
> 绿宝石：这玩意我出三个土块儿

有原谅梗了（
不知道这个行不行

**Comment by XxLittleCxX** [comment]
> > 绿宝石：这玩意我出三个土块儿
> 
> 有原谅梗了（
> 不知道这个行不行，我看看别人怎么想。

会不会太长了些，一般来说有长度限制吗

**Comment by lakejason0** [comment]
> > > 绿宝石：这玩意我出三个土块儿
> > 
> > 
> > 有原谅梗了（
> > 不知道这个行不行，我看看别人怎么想。
> 
> 会不会太长了些，一般来说有长度限制吗

【你知道吗】这玩意的标准译名是“被虫蚀的石砖”，而不是什么鬼玩意。

**Comment by lakejason0** [comment]
我提一个吧，锁链盔甲->蕾丝套。
居然没人提过。

**Comment by dujinhuachinaeddie** [comment]
哦？不错

> 我提一个吧，锁链盔甲->蕾丝套。
> 居然没人提过。

**Comment by lakejason0** [comment]
多提一提吧，量积累到一定程度我帮忙开一个pr。

**Comment by dujinhuachinaeddie** [comment]
大家挺有文化猪gāng liè （打不出来也懒得打）都出来了

**Comment by lakejason0** [comment]
> 大家挺有文化猪gāng liè （打不出来也懒得打）都出来了

常规梗了都（
绿宝石那个我不知道统一性（consistency）怎么样，个人认为还行。

**Comment by dujinhuachinaeddie** [comment]
潜影贝：缺乏珍珠的贝

**Comment by dujinhuachinaeddie** [comment]
> 潜影贝：缺乏珍珠的贝

感觉有点牵强，我想办法改一改

**Comment by lakejason0** [comment]
> > 潜影贝：缺乏珍珠的贝
> 
> 感觉有点牵强，我想办法改一改

注：盒子已经改成傻瓜盒子了，但是潜影贝还没

**Comment by dujinhuachinaeddie** [comment]
火云邪神有了吗

**Comment by lakejason0** [comment]
> 火云邪神有了吗

由于和赤脚大仙冲突所以干脆改成炫迈兽了

**Comment by dujinhuachinaeddie** [comment]
我的世界：Q块世界

**Comment by dujinhuachinaeddie** [comment]
右手：麒麟臂

**Comment by lakejason0** [comment]
> 我的世界：Q块世界

不做。

**Comment by dujinhuachinaeddie** [comment]
蠹虫：银鱼

**Comment by lakejason0** [comment]
> 右手：麒麟臂

游戏中只有叫主副手（自定义皮肤设置除外），目前副手改成了废手

**Comment by lakejason0** [comment]
> 蠹虫：银鱼

蠢鱼

**Comment by dujinhuachinaeddie** [comment]
主手：麒麟臂

**Comment by dujinhuachinaeddie** [comment]
按照玩家习惯其实主手就是右手，除了某些左撇子改了设置之外

**Comment by lakejason0** [comment]
> 按照玩家习惯其实主手就是右手，除了某些左撇子改了设置之外

有人的左手才是麒麟臂哦……

**Comment by dujinhuachinaeddie** [comment]
我决定试一试雷石东版本1.3.1 ：D

**Comment by lakejason0** [comment]
> 我决定试一试雷石东版本1.3.1 ：D

有了，下一个

**Comment by dujinhuachinaeddie** [comment]
大火杆

**Comment by dujinhuachinaeddie** [comment]
流浪者：浪壳

**Comment by dujinhuachinaeddie** [comment]
冲击（附魔）：冲床

**Comment by dujinhuachinaeddie** [comment]
恶魂之泪：黑沉沉泪

**Comment by dujinhuachinaeddie** [comment]
弓：蝴蝶结
词翻译来自mc1.3.1

**Comment by dujinhuachinaeddie** [comment]
线：字符串
来自mc1.3.1

**Comment by dujinhuachinaeddie** [comment]
枯死的灌木：死了的布什

**Comment by dujinhuachinaeddie** [comment]
圆石：堆叠的岩石
来自mc RD-161607

**Comment by dujinhuachinaeddie** [comment]
木剑：暴徒优惠1.5伤害

**Comment by dujinhuachinaeddie** [comment]
栅栏：1.5个暴徒

**Comment by dujinhuachinaeddie** [comment]
有人吗？？

**Comment by dujinhuachinaeddie** [comment]
屏障方块：弗林特刚

**Comment by dujinhuachinaeddie** [comment]
正在治愈
快速冲锋
可疑的炖肉
导管
导管能量
模型
围墙
银鱼

**Comment by dujinhuachinaeddie** [comment]
平淡的=超平坦

**Comment by dujinhuachinaeddie** [comment]
威克斯

**Comment by lakejason0** [comment]
> 线：字符串
> 来自mc1.3.1

duplicate

**Comment by lakejason0** [comment]
> 枯死的灌木：死了的布什

duplicate

**Comment by lakejason0** [comment]
> 流浪者：浪壳

not considering

**Comment by lakejason0** [comment]
> 正在治愈
> 快速冲锋
> 可疑的炖肉
> 导管
> 导管能量
> 模型
> 围墙
> 银鱼

基翻够多了，这个大半duplicate，剩下的也不采用。

**Comment by lakejason0** [comment]
> 威克斯

猥傀

**Comment by lakejason0** [comment]
还有，尽量不要分这么多行。

**Comment by dujinhuachinaeddie** [comment]
ok

**Comment by lakejason0** [comment]
> 屏障方块：弗林特刚

没“立 入 禁 止”好

**Comment by lakejason0** [comment]
> 平淡的=超平坦

duplicate

**Comment by dianliang233** [comment]
太吵。有其他建议请直接编辑第一层来提出。

**Comment by lakejason0** [comment]
有其他建议请一次性编辑第一层来提出。

**Comment by Lxazl5770** [comment]
锁链盔甲->蕾丝套
恶魂之泪->黑沉沉泪
其他拒绝。
下次提建议先检查有无重复+学会编辑评论
谢谢理解。
