### ISSUE TITLE
更生草的建议

### ISSUE THREAD

**Issue by DUSIWEI-debug** [lakejason0/mcwzh-meme-resourcepack#90]
这个并没有全部中文，因此如果有些模组没有添加zh_meme.json的话，就没有办法显示中文，所以我建议把zh_cn.json改成zh_meme.json的内容

我希望终末之诗不要全是“e”，可以改一些更生草的对话，比如，谈谈Ff98sha和FtyLolipop的对话，说这作者太生草了（雾）

我真的希望把Pigstep改成猪灵抬棺

第一个建议就对英文渣很不友好，除非自行在模组里新建一个zh_meme.json

你往下翻干啥？

不许往下翻了！

另外，夹带一点私货
![私货](https://i.loli.net/2020/07/08/sU1gFbj3VfTwRIy.png)

**Comment by lakejason0** [comment]
>这个并没有全部中文，因此如果有些模组没有添加zh_meme.json的话，就没有办法显示中文，所以我建议把zh_cn.json改成zh_meme.json的内容

不确定你在说什么，你使用`_compatible`就好了。

**Comment by lakejason0** [comment]
> 我希望终末之诗不要全是“e”
现在也不是了啊

**Comment by lakejason0** [comment]
> 我真的希望把Pigstep改成猪灵抬棺

曲子已经改了，唱片名字主要是考虑一致性问题，我觉得可以改。

**Comment by DUSIWEI-debug** [comment]
> > 我希望终末之诗不要全是“e”
> > 现在也不是了啊

那……![批注 2020-07-08 151205.png](https://i.loli.net/2020/07/08/pwRsyGjKgSFTA4l.png)

**Comment by lakejason0** [comment]
> > > 我希望终末之诗不要全是“e”
> > > 现在也不是了啊
> 
> 那……![批注 2020-07-08 151205.png](https://camo.githubusercontent.com/828ff375ab3a72b09bb173f7cbf27016f18117be/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30372f30382f7077527379476a4b6753465441346c2e706e67)

请您更新。

**Comment by DUSIWEI-debug** [comment]
> > 这个并没有全部中文，因此如果有些模组没有添加zh_meme.json的话，就没有办法显示中文，所以我建议把zh_cn.json改成zh_meme.json的内容
> 
> 不确定你在说什么，你使用`_compatible`就好了。



> > > > 我希望终末之诗不要全是“e”
> > > > 现在也不是了啊
> > 
> > 
> > 那……![批注 2020-07-08 151205.png](https://camo.githubusercontent.com/828ff375ab3a72b09bb173f7cbf27016f18117be/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30372f30382f7077527379476a4b6753465441346c2e706e67)
> 
> 请您更新。

谢谢
