### ISSUE TITLE
红石中续器

### ISSUE THREAD

**Issue by chana-zcy** [lakejason0/mcwzh-meme-resourcepack#94]
名字改为 【雷石东直放站】
备注：
熟悉电影的应该对萨默·雷石东并不陌生，著名的《阿甘正传》《泰坦尼克号》都出自他的公司。

他一生传奇，在起起落落中终于成为业界神话。1972年，他还在一场火灾中被烧伤，但他并没有放弃奋斗，依旧自强不息。

MC中的雷石东正体现着他的精神：在雷暴中洗礼，迎着初升的太阳，向世界传递能量。因此官方对雷石东的偏爱是有原因的。虽然删掉它的确可惜，但为了红石系统的强大，必要的牺牲也是要做出的。

**Comment by AlPha5130** [comment]
梗体不治眼瞎，自己去游戏里看看。

**Comment by chana-zcy** [comment]
> 梗体不治眼瞎，自己去游戏里看看。

我没下正确啊
