### ISSUE TITLE
中国访问太慢

### ISSUE THREAD

**Issue by dujinhuachinaeddie** [lakejason0/mcwzh-meme-resourcepack#95]
中国访问GitHub太慢，像我一样可以科学上网的也罢了，可很多人都极慢。
建议使用gitee
我有一个备份仓库：
https://gitee.com/incimathcal/mcwzh-meme-resourcepack
建议采纳

**Comment by XxLittleCxX** [comment]
能保证长期/自动更新吗，感觉没有太大必要，也不是主要用来托管下载的地方

**Comment by dujinhuachinaeddie** [comment]
不能算了
